name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hardhat:
    strategy:
      fail-fast: true

    name: Hardhat project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Compile
        run: yarn compile

      - name: Run Hardhat tests
        run: |
          yarn test
        id: hardhat-test
